# Generated by Django 3.0 on 2022-04-12 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0002_auto_20220412_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifepost',
            name='gitee_url',
        ),
        migrations.RemoveField(
            model_name='lifepost',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='lifepost',
            name='other_url',
        ),
    ]
