# Generated by Django 3.0 on 2022-04-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_articlepost_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecolumn',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
