# Generated by Django 3.0 on 2022-04-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='bg', max_length=100)),
                ('url', models.URLField(default='https://space.bilibili.com/490457522')),
                ('avatar', models.URLField(default='https://s1.ax1x.com/2022/04/11/LEjUYV.jpg')),
            ],
        ),
    ]
