# Generated by Django 3.0 on 2022-04-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myself', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlink',
            name='title',
            field=models.CharField(default='Bilibili', max_length=100),
        ),
    ]
