# Generated by Django 3.0 on 2022-04-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myself', '0003_auto_20220412_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlink',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='friendlink',
            name='title',
            field=models.CharField(default='Bilibili', max_length=100),
        ),
    ]
