# Generated by Django 3.0 on 2022-04-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscriptspost',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='scholar/%Y%m%d/'),
        ),
    ]
