# Generated by Django 3.0 on 2022-04-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0002_auto_20220410_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscriptspost',
            name='avatar',
            field=models.URLField(default='https://s1.ax1x.com/2022/04/11/LEjUYV.jpg'),
        ),
    ]
