# Generated by Django 3.0 on 2022-04-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpost',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='project/%Y%m%d/'),
        ),
    ]
