# Generated by Django 3.0 on 2022-04-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20220412_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesbg',
            name='title',
            field=models.CharField(default='bg', max_length=100),
        ),
    ]
