# Generated by Django 3.0 on 2022-04-11 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0003_lifecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifecomment',
            name='Life',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lifecomments', to='life.LifePost'),
        ),
        migrations.AddField(
            model_name='lifecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lifecomments', to=settings.AUTH_USER_MODEL),
        ),
    ]
