# Generated by Django 3.0 on 2022-04-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20220411_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lifecomment',
            old_name='Life',
            new_name='life',
        ),
    ]
